
module.exports = async (client, interaction, args) => {

    const user = interaction.options.getUser('utilisateur');

    if (!user) return client.errUsage({ usage: "kill [mention user]", type: 'editreply' }, interaction);

    var kills = [
        `Après une longue journée, il s'installe sur le canapé avec ${user} et regarde The Big Bang Theory. Après une blague de Sheldon Cooper, ${user} rit de façon incontrôlable en mourant.`,
        `${interaction.user} a fait Alt+F4 sur ${user}.exe !`,
        `${interaction.user} a tenté de jouer de la flûte, faisant exploser la tête de ${user}.`,
        `${interaction.user} s'est fait exploser les tympans en écoutant de la musique trop fort.`,
        `${interaction.user} défie ${user} dans un combat à mort. ${user} gagne.`,
        `${interaction.user} coupe la tête de ${user} avec un clavier.`,
        `${interaction.user} écrase ${user} avec un frigo.`,
        `${interaction.user} décapite ${user} avec une épée.`,
        `${interaction.user} tire les oreilles de ${user} trop fort et les arrache.`,
        `${interaction.user} noie ${user} dans un tonneau de bière.`,
        `${interaction.user} noie ${user} dans une baignoire de chocolat chaud. *Comment était ton dernier verre?*`,
        `${interaction.user} éviscère ${user} avec un couteau à beurre rouillé. Aïe !`,
        `${interaction.user} donne des oreos remplis de dentifrice à ${user}, qui était apparemment allergique au fluor. GGWP.`,
        `${interaction.user} est tombée amoureuse de ${user} puis lui a littéralement brisé le coeur.`,
        `${interaction.user} tire une dinde congelée supersonique sur ${user}, le tuant instantanément.`,
        `${interaction.user} J'ai oublié de laisser la fenêtre de la porte de la voiture ouverte et ${user} meurt de surchauffe.`,
        `${interaction.user} a oublié de protéger la pelouse de ${user} contre les zombies... On dirait que les zombies ont fait un festin la nuit dernière.`,
        `${interaction.user} a demandé à ${user} de regarder un anime avec lui. ${user} ne pouvait pas le supporter.`,
        `${interaction.user} prend ${user} et le met dans une machine de congélation automatique avec du jus et règle la température à 100 Kelvin, créant ainsi des glaces humaines.`,
        `${interaction.user} m'a engagé pour te tuer, mais je ne veux pas ! ${user}`,
        `${interaction.user} a étreint ${user} trop fort..`,
        `${interaction.user} hulk réduit ${user} en bouillie.`,
        `${interaction.user} a tué ${user} en arrachant la peau de son visage et en en faisant un masque.`,
        `${interaction.user} tue ${user} après des heures de torture.`,
        `${interaction.user} tue ${user} avec un chandelier dans l'étude`,
        `${interaction.user} tue ${user} avec gentillesse`,
        `${interaction.user} tue ${user} avec son propre pied.`,
        `${interaction.user} assassine ${user} avec une hache.`,
        `${interaction.user} a appuyé sur delete. Ça a supprimé ${user}`,
        `${interaction.user} pousse ${user} dans le vide froid de l'espace.`,
        `${interaction.user} écrase ${user} avec un PT Cruiser.`,
        `${interaction.user} tire sur ${user} dans la tête.`,
        `${interaction.user} tire dans la bouche de ${user} avec un laser arc-en-ciel, ce qui fait exploser la tête de ${user} avec des arcs-en-ciel et ${user} renaît en licorne. :unicorn:`,
        `${interaction.user} tué ${user} en utilisant la base Starkiller !`,
        `${interaction.user} met de l'eau de javel dans la limonade de ${user}.`,
        `${interaction.user} a étranglé ${user}.`,
        `${interaction.user} attache ${user} à un ICBM et l'envoie en Corée du Nord avec.`,
        `${interaction.user} frappe ${user} avec la malédiction qui tue... *Avada Kedavra!*`,
        `${interaction.user} arrache les lèvres de ${user} après un baiser.`,
        `${interaction.user} thicc et effondre la cage thoracique de ${user}.`,
        `${interaction.user} essaie de tirer sur le côté large d'une grange, le rate et touche ${user} à la place.`,
        `${interaction.user} met Goosebumps (film de 2015) à la télé. ${user} étant un chat effrayé, meurt d'une crise cardiaque.`,
        `${interaction.user} était tellement swag que ${user} en est mort. #Swag`,
        `${interaction.user}, vous êtes sûr de vouloir tuer ${user} ? Il m'a l'air gentil.`,
        `${user} a accidentellement cliqué sur une publicité popup qui dit : \Les médecins nous détestent, découvrez la meilleure astuce pour mourir aujourd'hui !\``,
        `${user} ont trébuché accidentellement et sont morts en se levant pour écrire leur lettre de suicide.`,
        `${user} ont mangé un morceau de beurre exotique. C'était tellement incroyable que ça les a tués.`,
        `${user} a mangé une pomme et il s'est avéré qu'elle était faite de cire. Quelqu'un est mort d'empoisonnement à la cire plus tard ce jour-là.`,
        `${user} a mangé trop de laxatifs et s'est noyés dans leur propre merde. Ew.`,
        `${user} se vide de son sang après avoir essayé de monter \`Les moments les plus stupides des péquenauds\`.`,
        `${user} ne peut pas être tué, car c'est un fantôme.`,
        `${user} s'est étouffé dans une poubelle.`,
        `${user} s'est étouffé avec un os de poulet.`,
        `${user} s'est étouffé avec des cheerios et meurt. Quel idiot...`,
        `${user} a allumé le système de musique pour réaliser que le volume était au maximum et que la chanson jouée était Baby de Justin Beiber...`,
        `${user} vomit dans son œil, devient aveugle, court pour chercher de l'aide mais fonce sur les voies ferrées et se fait écraser par un train.`,
        `${user} a décidé que c'était une bonne idée de combattre un tigre en sentant la viande. Ça n'a pas bien fini.`,
        `${user} est mort après avoir joué pendant 90 heures d'affilée sans bouger ni manger.`,
        `${user} est mort après avoir joué avec un hand spinner en forme de lame de rasoir.`,
        `${user} est mort après avoir réalisé à quel point sa grammaire était merdique.`,
        `${user} est mort après avoir essayé de surpasser Dank Memer.`,
        `${user} est mort d'une mort honorable. Mort par snoo snoo.`,
        `${user} est mort parce que RemindMeBot a oublié de leur rappeler de respirer.`,
        `${user} est mort parce qu'il a commencé à jouer avec un hand spinner mais il a réalisé qu'on était en 2016 alors ils ont commencé à se brancher sur la vieille sorcière dans Blanche Neige et Obama a commencé à tondre leur pelouse et ils ont sauté par la fenêtre et se sont fait déchiqueter par la tondeuse d'Obama.`,
        `${user} est mort à cause de ${interaction.user} qui était si stupide`,
        `${user} est mort après avoir mangé beaucoup trop de hot-dogs en préparation de son rendez-vous.`,
        `${user} est mort en mangeant du poisson cru périmé et infecté avec le riz le plus dégoûtant du monde en guise de sushi, tout en étant constamment poignardé dans le scrotum avec un clou de 10 cm assez pointu pour traverser le kevlar. La sauce soja était de la pisse de chat.`,
        `${user} est mort à cause d'une consommation élevée de sel`,
        `${user} est mort d'un coup de pied rapide au cerveau.`,
        `${user} est mort d'une quantité tragique de mauvais sucres.`,
        `${user} est mort en faisant le défi du seau de glace.`,
        `${user} est mort d'avoir bu trop d'eau Huh, je suppose que c'est possible !`,
        `${user} est mort d'avoir mangé des aiguilles de cactus.`,
        `${user} est mort d'avoir mangé trop de pain :/`,
        `${user} est mort d'Ebola.`,
        `${user} est mort d'une overdose de memes :/`,
        `${user} est mort d'avoir chié pendant 36 heures d'affilée.`,
        `${user} est mort d'avoir avalé des pierres trop vite`,
        `${user} est mort de trop de coups de soleil.`,
        `${user} est mort d'une overdose de sucre`,
        `${user} est mort en testant une bombe à hydrogène. Il n'y a plus rien à enterrer.`,
        `${user} est mort en écoutant 'It's every day bro'.`,
        `${user} est mort en jouant à la marelle sur des mines terrestres apparemment désactivées.`,
        `${user} est mort en essayant de trouver la ville d'Angleterre`,
        `${user} est mort. OOF`,
        `${user} meurt après avoir avalé un cure-dent.`,
        `${user} meurt aux mains de ${interaction.user}.`,
        `${user} meurt parce qu'elle a utilisé une épingle à cheveux pour soulever ses cils.`,
        `${user} meurt parce qu'il était juste trop en colère.`,
        `${user} meurt en jurant sur un serveur Minecraft chrétien`,
        `${user} meurt par manque d'amis.`
        `${user} meurt en tamponnant trop fort.`,
        `${user} meurt d'avoir manqué de respect aux wahmen.`,
        `${user} meurt en postant des memes normaux.`,
        `${user} meurt d'une aversion sévère pour le sable. Il est grossier, rugueux et irritant, il s'infiltre partout.`,
        `${user} meurt d'avoir regardé le film Emoji et de l'avoir apprécié.`,
        `${user} meurt dans un horrible accident, et il a été conçu par ${interaction.user}.`,
        `${user} meurt au nord du mur et se transforme en marcheur blanc.`,
        `${user} meurt du sida.`,
        `${user} meurt de la dysenterie.`,
        `${user} meurt de causes naturelles.`,
        `${user} meurt de faim.`,
        `${user} meurt dans le couloir de la mort par injection létale après avoir assassiné ${interaction.user} et sa famille.`,
        `${user} meurt.`,
        `Après une lutte, ${user} tue ${interaction.user}`,
        `${user} a disparu de l'univers.`,
        `${user} a bu du soda toxique avant qu'il ne s'en soit rappelé.`,
        `${user} a fait tomber un téléphone Nokia sur son visage et lui a fendu le crâne.`,
        `${user} noyés dans ses propres larmes.`,
        `${user} mange trop de copypasta et explose`,
        `${user} est tombé d'une falaise en jouant à Pokemon Go. Bon travail pour garder ton nez dans ce minuscule téléphone. :iphone:`,
        `${user} est tombé dans une fosse de féministes en colère.`,
        `${user} se fait renverser par une voiture.`,
        `${user} se fait poignarder par ${interaction.user}`,
        `${user} s'est fait frappé par la foudre.`,
        `${user} s'est battu au couteau avec le Pape. L'un d'eux est en enfer maintenant.`,
        `${user} s'est fait marcher dessus par un éléphant.`,
        `${user} a eu une attaque après une triste et misérable existence. Ils sont ensuite dévorés par leurs amples chats.`,
        `${user} a été reconnu coupable, il est temps de les exécuter !`,
        `${user} mange de la mauvaise nourriture chinoise, et en paie le prix fort.`,
        `${user} est enlevé par des extraterrestres, et le gouvernement les tue pour étouffer l'affaire.`,
        `${user} est mort des mains de ${interaction.user}.`,
        `${user} est injecté de sirop de chocolat, ce qui le transforme en une personne faite de chocolat. Alors qu'ils travaillent à temps partiel à la garderie, ils sont dévorés par les bébés affamés. :chocolate_bar:`,
        `${user} est tué par un lapin avec une mèche vicieuse d'un kilomètre de large.`,
        `${user} est mort par sa propre stupidité.`,
        `${user} a été tué dans un braquage qui a mal tourné.`,
        `${user} ne peut pas être tué. Oh, attendez, non, ${interaction.user} le tue quand même.`,
        `${user} est si stupide qu'il s'est étouffé avec son oxygène.`,
        `${user} est empaqueté dans un costume par Freddy pendant leur garde de nuit. Oh, pas encore ces animatronics !`,
        `${user} est aspiré dans Minecraft. ${user}, étant un noob à la soi-disant Real-Life Minecraft fait face à l'écran Game Over.`,
        `${user} se sont tués après avoir vu les memes normaux que ${interaction.user} poste.`,
        `${user} se tue après avoir réalisé à quel point ${interaction.user} est stupide.`,
        `${user} vit, malgré la tentative de meurtre de ${interaction.user}.`,
        `${user} perd la volonté de vivre`,
        `${user} appuie sur un bouton aléatoire et est téléporté à une hauteur de 100 m, ce qui lui permet de tomber vers sa mort inévitable. Morale de l'histoire : Ne vous promenez pas en appuyant sur des boutons au hasard.`,
        `${user} lit des memes jusqu'à la mort.`,
        `${user} s'est arraché le cœur..`,
        `${user} a arraché son propre cœur pour montrer son amour pour ${interaction.user}.`,
        `${user} hurle de terreur en frayant accidentellement avec Cthulhu tout en prononçant des mots latins aléatoires. Cthulhu attrape ${user} par la jambe droite et l'emmène dans sa dimension en hurlant, \`Chérie, le dîner est prêt !\``,
        `${user} a glissé dans la salle de bain et s'est étouffé avec le rideau de la douche.`,
        `${user} glisse sur une peau de banane et tombe dans les escaliers.`,
        `${user} fait tourner un hand spinner et quand il s'arrête, il meurt...`,
        `${user} meurt, tué par le killer bunny`,
        `${user} prend une flèche dans le genou. Et partout ailleurs.`,
        `${user} a répondu aux modérateurs et a été détruit par le marteau de bannissement.`,
        `${user} fait basculer son chapeau trop loin et tombe sur les rails d'un métro qui arrive.`,
        `${user} a essayé de faire de l'artisanat, mais il s'est coupé accidentellement avec les ciseaux..:scissors:`,
        `${user} a essayé de devenir célèbre sur YouTube en diffusant en direct un truc débile. Du parachutisme en étant enchaîné à un frigo.`,
        `${user} a essayé de distancer un train, le train a gagné.`,
        `${user} a essayé de choisir le Saint Graal. Il a choisi... mal.`,
        `${user} trébuche sur ses propres lacets de chaussures et meurt.`,
        `${user} s'est opposé vocalement aux Clinton, puis a soudainement disparu.`,
        `${user} était un résident d'Alderaan avant que Dark Vador ne détruise la planète...`,
        `${user} a été accusé d'avoir volé la couronne de Neptune...`,
        `${user} chargeait son Samsung Galaxy Note 7...`,
        `${user} a été mangé vivant par des fourmis`,
        `${user} a eu l'occasion de synthétiser l'élément 119 (Ununennium) et de lui donner son nom, mais il s'est planté. R.I.P.`,
        `${user} a été tué par ${interaction.user} avec des lingettes pour bébé.`,
        `${user} a été assassiné par ${interaction.user} et tout le monde le sait, mais il n'y a aucune preuve.`,
        `${user} a été téléporté dans la réalité de Jurassic World et a été dévoré vivant par l'Indominus Rex.`,
        `${user} a été jeté dans le broyeur d'un camion poubelle par ${interaction.user}.`,
        `${user} marchait normalement quand, du coin de l'œil, il a vu quelqu'un faire un bottle flip et dab, provoquant une attaque chez ${user}.`,
        `${user} a regardé le film Emoji et est mort de dégoût.`,
        `${user} a fait un tour avec un ballon de plomb.`,
        `Après avoir été poussé dans l'océan par ${interaction.user}, ${user} est mangé par un requin.`,
        `Après que le raid des enfants de Roblox soit entré dans le serveur, ${user} est mort d'un cancer.`,
        `Sida, ${user} est mort du sida.`,
        `En invoquant les pouvoirs divins, ${interaction.user} frappe ${user} et ses coutumes païennes.`,
        `Dans une tournure soudaine des événements, je ne tue pas ${user}.`,
        `Non.`,
        `Notre seigneur et sauveur Gaben frappe ${user} avec un éclair.`,
        `Désolé, ${interaction.user}, je n'aime pas tuer les gens.`,
        `La balle a manqué Harambe et a touché ${user} à la place. Hourra pour Harambe !`,
        `En effectuant une coloscopie sur un éléphant, ${user} se coince la tête dans le rectum de l'éléphant et s'étouffe.`,
    ];

    client.embed({ title: `🔫・Meurtre`, desc: `${kills[Math.floor(Math.random() * kills.length)]}`, type: 'editreply' }, interaction)

}

     